version: "3.9"
services:
  web:
    image: pkboom/simple-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./files:/files
      - storage:/storage

volumes:
  storage:
    external: true
