version: "3.9"

services:
  web:
    image: simple-docker:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev # override command in Dockerfile
    # command: ["npm", "run", "dev"]
    ports:
      - 3000:3000
    volumes:
      # map the current directory to /app inside the container
      # in this case, you have to run `npm install` before running `docker-compose up`
      - .:/app
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: simple-docker
      MYSQL_ROOT_PASSWORD: password
    volumes:
      # docker db is mapped to a volume, so now db data is not volatile
      - mysql_db:/var/lib/mysql

volumes:
  mysql_db:
